In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [3]:
df=pd.read_csv('/content/drive/MyDrive/data analytics netflix/Copy of combined_data_1.txt.zip',header=None,names=['Cust_id','Rating'],usecols=[0,1])
df

          Cust_id  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [4]:
df.head(100)

    Cust_id  Rating
0        1:     NaN
1   1488844     3.0
2    822109     5.0
3    885013     4.0
4     30878     4.0
..      ...     ...
95  1245406     4.0
96  1834590     3.0
97   593225     3.0
98  1011918     4.0
99  1665054     4.0

[100 rows x 2 columns]

#Movie count
#customer count
#ratings count
#start count

In [5]:
df.isnull().sum()

Cust_id       0
Rating     4499
dtype: int64

In [6]:
movie_count=df.isnull().sum()['Rating']
movie_count

4499

In [7]:
total_uni=df['Cust_id'].nunique()
total_uni

475257

In [8]:
cust_count=total_uni-movie_count
cust_count

470758

In [9]:
rating_count=df['Rating'].count()
rating_count

24053764

In [10]:
stars_count=df['Rating'].value_counts()
stars_count

Rating
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [11]:
movie_id=None
movie_list=[]

for customer in df['Cust_id']:
  if ":" in customer:
    movie_id=int(customer.replace(":",""))

  movie_list.append(movie_id)

In [12]:
movie_list

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [13]:
df['Movie_ID']=movie_list
df

          Cust_id  Rating  Movie_ID
0              1:     NaN         1
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24058263 rows x 3 columns]

In [14]:
df.dropna(inplace=True)

In [15]:
df

          Cust_id  Rating  Movie_ID
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
5          823519     3.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24053764 rows x 3 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_id   object
 1   Rating    float64
 2   Movie_ID  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [17]:
df['Cust_id']=df['Cust_id'].astype(int)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_id   int64
 1   Rating    float64
 2   Movie_ID  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

# less no.of rating -> drop those movie
# less no.of ratings by customer -> droped

# 6: -> 3500  --> 78 percentile  --> movie 6 is above 78 percent of movie rating count
# top 40% -> 60 pernctile , value >=60 percnetile

# 100 --> 98 -> 98%
# 100--> 98(highest) -> 99.99999999

In [19]:
movie_rat_count=df['Movie_ID'].value_counts()
movie_rat_count

Movie_ID
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [20]:
bench_mark1=round(movie_rat_count.quantile(0.6),0)
bench_mark1

908.0

In [21]:
drop_movie_index=movie_rat_count[movie_rat_count<bench_mark1].index
drop_movie_index

Index([1598, 1733, 1647, 4099, 1616, 1446,  263, 4259,  160, 1988,
       ...
       1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
      dtype='int64', name='Movie_ID', length=2699)

In [22]:
cust_rat_count= df['Cust_id'].value_counts()

In [23]:
cust_rat_count

Cust_id
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
1300341       1
2550360       1
11848         1
930788        1
594210        1
Name: count, Length: 470758, dtype: int64

In [24]:
bench_mark2=round(cust_rat_count.quantile(0.6),0)
bench_mark2

36.0

In [25]:
drop_cust_index=cust_rat_count[cust_rat_count<bench_mark2].index
drop_cust_index

Index([2194851,  600295, 1739398, 1157368,  532108, 2157249,  256134,  640441,
       1272324, 1346990,
       ...
       1969065,  899932,  611596, 2147176,  811650, 1300341, 2550360,   11848,
        930788,  594210],
      dtype='int64', name='Cust_id', length=282042)

In [26]:
drop_movie_index,drop_cust_index

(Index([1598, 1733, 1647, 4099, 1616, 1446,  263, 4259,  160, 1988,
        ...
        1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
       dtype='int64', name='Movie_ID', length=2699),
 Index([2194851,  600295, 1739398, 1157368,  532108, 2157249,  256134,  640441,
        1272324, 1346990,
        ...
        1969065,  899932,  611596, 2147176,  811650, 1300341, 2550360,   11848,
         930788,  594210],
       dtype='int64', name='Cust_id', length=282042))

In [27]:
#SVD -> Opps , Cross validation, Matrix Decompsition

In [28]:
# Filter out movies with low ratings
df = df[~df['Movie_ID'].isin(drop_movie_index)]
# Filter out customers with low rating activity
df = df[~df['Cust_id'].isin(drop_cust_index)]

In [29]:
df

          Cust_id  Rating  Movie_ID
696        712664     5.0         3
697       1331154     4.0         3
698       2632461     3.0         3
699         44937     5.0         3
700        656399     4.0         3
...           ...     ...       ...
24056842  1055714     5.0      4496
24056843  2643029     4.0      4496
24056844   267802     4.0      4496
24056845  1559566     3.0      4496
24056846   293198     3.0      4496

[19695836 rows x 3 columns]

In [30]:
import pandas as pd
movie_title=pd.read_csv('/content/drive/MyDrive/data analytics netflix/Copy of movie_titles.csv',encoding='ISO-8859-1',header=None,names=['Movie_ID','Year','Name'], engine='python', on_bad_lines='skip')
movie_title.set_index('Movie_ID',inplace=True)
movie_title.head()

            Year                          Name
Movie_ID
1         2003.0               Dinosaur Planet
2         2004.0    Isle of Man TT 2004 Review
3         1997.0                     Character
4         1994.0  Paula Abdul's Get Up & Dance
5         2004.0      The Rise and Fall of ECW

In [31]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-linux_x86_64.whl size=2554985 sha256=5aa503707d38398a592f7bfd984112c6b629d9c9cbb791ae9aa45e1a1d657c60
  Stored in directory: /root/.cache/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

In [32]:
movie_title

            Year                                               Name
Movie_ID
1         2003.0                                    Dinosaur Planet
2         2004.0                         Isle of Man TT 2004 Review
3         1997.0                                          Character
4         1994.0                       Paula Abdul's Get Up & Dance
5         2004.0                           The Rise and Fall of ECW
...          ...                                                ...
17766     2002.0  Where the Wild Things Are and Other Maurice Se...
17767     2004.0                  Fidel Castro: American Experience
17768     2000.0                                              Epoch
17769     2003.0                                        The Company
17770     2003.0                                       Alien Hunter

[17434 rows x 2 columns]

In [33]:
from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate

In [34]:
reader=Reader()

In [35]:
data=Dataset.load_from_df(df[['Movie_ID','Cust_id','Rating']][:100000],reader)

In [36]:
data

In [37]:
model=SVD()

In [38]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.02385792, 1.01153994, 1.02051253]),
 'fit_time': (1.48856520652771, 1.3972032070159912, 1.5607478618621826),
 'test_time': (0.15186524391174316, 0.44854259490966797, 0.26244139671325684)}

In [39]:
#1331154
user_1331154=df[df['Cust_id']==1331154]
user_1331154

          Cust_id  Rating  Movie_ID
697       1331154     4.0         3
5178      1331154     4.0         8
31460     1331154     3.0        18
92840     1331154     4.0        30
224761    1331154     3.0        44
...           ...     ...       ...
23439584  1331154     4.0      4389
23546489  1331154     2.0      4402
23649431  1331154     4.0      4432
23844441  1331154     3.0      4472
23985561  1331154     4.0      4488

[253 rows x 3 columns]

In [40]:
dummy_title=movie_title.copy()

In [41]:
dummy_title

            Year                                               Name
Movie_ID
1         2003.0                                    Dinosaur Planet
2         2004.0                         Isle of Man TT 2004 Review
3         1997.0                                          Character
4         1994.0                       Paula Abdul's Get Up & Dance
5         2004.0                           The Rise and Fall of ECW
...          ...                                                ...
17766     2002.0  Where the Wild Things Are and Other Maurice Se...
17767     2004.0                  Fidel Castro: American Experience
17768     2000.0                                              Epoch
17769     2003.0                                        The Company
17770     2003.0                                       Alien Hunter

[17434 rows x 2 columns]

In [42]:
est_rating=[]
for movie in dummy_title.index:
  rating=model.predict(1331154,movie).est
  est_rating.append(rating)

dummy_title['Rating']=est_rating

In [43]:
dummy_title

            Year                                               Name    Rating
Movie_ID
1         2003.0                                    Dinosaur Planet  3.579792
2         2004.0                         Isle of Man TT 2004 Review  3.579792
3         1997.0                                          Character  3.579792
4         1994.0                       Paula Abdul's Get Up & Dance  3.579792
5         2004.0                           The Rise and Fall of ECW  3.579792
...          ...                                                ...       ...
17766     2002.0  Where the Wild Things Are and Other Maurice Se...  3.579792
17767     2004.0                  Fidel Castro: American Experience  3.579792
17768     2000.0                                              Epoch  3.579792
17769     2003.0                                        The Company  3.579792
17770     2003.0                                       Alien Hunter  3.579792

[17434 rows x 3 columns]

In [44]:
dummy_title=dummy_title.sort_values('Rating',ascending=False)
dummy_title.head()

            Year                              Name    Rating
Movie_ID
13875     1982.0  Gilbert and Sullivan: The Mikado  3.858547
17451     2000.0                Along for the Ride  3.854599
13511     1993.0            Much Ado About Nothing  3.833650
6071      2001.0                        Fausto 5.0  3.811342
5727      1984.0              The Last Starfighter  3.792924

In [45]:
# DL-> Actors , Drectors , year, trend, latest realse

# hw -> recomend for any 5 users